Add bind function to logger
nuclio/nuclio-sdk-py pull request #5
Opened 2020-02-16 17:26 UTC by sahare92

2020-02-16 17:55 UTC, omesser approved these changes

2020-02-16 18:11 UTC, omesser requested changes

2020-02-16 18:11 UTC, omesser commented on nuclio_sdk/logger.py
> +        self._logger._log(level, msg, args, extra={'with': kw_args})
message > msg

2020-02-17 07:22 UTC, liranbg commented on nuclio_sdk/logger.py
> +        self._logger._log(level, message, args, extra={'with': kw_args})
that will turn every usage of `info` and `info_with` to `info_with`
consider checking if kwargs is not empty and then provide it with  `extra`
something like `extra = {'with': kw_args } if kw_args else None`

2020-02-17 12:50 UTC, omesser approved these changes

2020-02-17 12:51 UTC, merged