Add support for batch deserialization
nuclio/nuclio-sdk-py pull request #65
Opened 2024-04-17 15:45 UTC by rokatyy

This PR adds support of `[Event]` or, in other words, `batch` deserialisation

2024-04-17 17:57 UTC, TomerShor requested changes

2024-04-17 17:57 UTC, TomerShor commented on nuclio_sdk/event.py
> +            return _decode_single_event(parsed_data)
to reduce *a bit* of the code dup, perhaps move this to a private method of the base `_EventDeserializer` that gets the data and the decoding function for a single event.
Something like `decode_single_or_list_event`.
Then use it in all 3 instances of this PR

2024-04-17 17:57 UTC, TomerShor commented on nuclio_sdk/test/test_event.py
> +        )
in general, try using more variables instead of explicit strings so the test will be more resilient to changes.
e.g - changing the event body / trigger name will require chaging only in one place instead of 3 / 4.

2024-04-18 07:38 UTC, rokatyy commented on nuclio_sdk/event.py
> +            return _decode_single_event(parsed_data)
@TomerShor cool idea!

2024-04-18 14:01 UTC, TomerShor requested changes

2024-04-18 14:01 UTC, TomerShor commented on nuclio_sdk/event.py
> +    def decode_single_or_list_event(parsed_data, decode_single_event):
```suggestion
    def decode_single_or_list_event(parsed_data, decode_single_event_function):
```

2024-04-21 06:04 UTC, TomerShor requested changes

2024-04-21 06:04 UTC, TomerShor commented on nuclio_sdk/event.py
> +            return _decode_single_event(parsed_data)
```suggestion
        return self.decode_single_or_list_event(parsed_data, _decode_single_event)
```

2024-04-21 08:58 UTC, TomerShor commented on nuclio_sdk/event.py
> +        return self.decode_single_or_list_event(parsed_data, _decode_single_event)
need to remove the `@staticmethod` decorator for that

2024-04-21 08:59 UTC, TomerShor approved these changes

2024-04-21 09:32 UTC, merged